export const jobTypes = [
  "Internship",
  "Freelance",
  "Full-Time",
  "Part-Time",
  "Contract",
  "Temporary",
  "Remote",
  "Consultant",
  "Volunteer",
  "Apprenticeship",
  "Probationary",
  "Shift-Based",
];

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
  "Ladakh",
  "Jammu and Kashmir",
];

export const companyTypes = [
  "Start-ups",
  "MNCs",
  "SMEs",
  "Government",
  "Non-profit",
  "Public Sector Undertakings (PSUs)",
  "Educational Institutions",
  "Research Organizations",
  "NGOs",
  "Corporate Firms",
  "Cooperatives",
  "BPO/KPO",
  "E-commerce",
];

export const industries = [
  "IT",
  "Medical",
  "Finance",
  "Education",
  "Manufacturing",
  "Retail",
  "Hospitality",
  "Agriculture",
  "Automotive",
  "Telecommunication",
  "Construction",
  "Media & Entertainment",
  "Energy & Utilities",
  "Logistics & Transportation",
  "Healthcare & Pharmaceuticals",
  "Real Estate",
  "Tourism",
  "Banking",
  "Insurance",
  "Legal Services",
  "Human Resources",
  "Public Relations",
  "Event Management",
  "Textiles",
  "Food & Beverage",
  "Mining",
  "Aerospace & Defense",
  "Arts & Crafts",
  "Electronics & Appliances",
];

export const domains = [
  "Data Analyst",
  "Full Stack Web Developer",
  "SDE",
  "QA Engineer",
  "Network Engineer",
  "Cybersecurity Specialist",
  "Digital Marketing Specialist",
  "SEO Analyst",
  "UX/UI Designer",
  "Product Manager",
  "Business Analyst",
  "Project Manager",
  "Content Writer",
  "Data Scientist",
  "Machine Learning Engineer",
  "DevOps Engineer",
  "Mobile App Developer",
  "Cloud Architect",
  "Technical Support Specialist",
  "Database Administrator",
  "HR Manager",
  "Finance Manager",
  "Operations Manager",
  "Graphic Designer",
  "Public Relations Manager",
  "Supply Chain Manager",
  "Legal Advisor",
  "Medical Officer",
  "Research Scientist",
  "Teacher/Professor",
  "Customer Support Executive",
];
